modulelist=com.p6spy.engine.spy.P6SpyFactory
driverlist=com.mysql.cj.jdbc.Driver
outagedetection=true
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.MultiLineFormat
