CREATE TABLE IF NOT EXISTS t_attendance (
    id BIGINT NOT NULL PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    branch_id BIGINT NOT NULL,
    lesson_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    status TINYINT NOT NULL DEFAULT 2 COMMENT '2=已入园 3=已离园 4=缺勤 5=请假',
    check_in_at DATETIME(3) NULL,
    check_out_at DATETIME(3) NULL,
    check_in_method VARCHAR(16) NULL COMMENT 'manual/qr/auto/face_reserved',
    note VARCHAR(256) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    version INT NOT NULL DEFAULT 1,
    UNIQUE KEY uk_attendance_lesson_student (tenant_id, lesson_id, student_id, deleted_at),
    KEY idx_attendance_branch_lesson (tenant_id, branch_id, lesson_id),
    KEY idx_attendance_student_lesson (student_id, lesson_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_pickup_record (
    id BIGINT NOT NULL PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    branch_id BIGINT NOT NULL,
    attendance_id BIGINT NOT NULL,
    event_type VARCHAR(8) NOT NULL COMMENT 'in/out',
    guardian_id BIGINT NULL,
    is_abnormal TINYINT NOT NULL DEFAULT 0,
    abnormal_note VARCHAR(256) NULL,
    event_time DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    version INT NOT NULL DEFAULT 1,
    KEY idx_pickup_attendance (attendance_id),
    KEY idx_pickup_branch_time (tenant_id, branch_id, event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS t_leave_request (
    id BIGINT NOT NULL PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    branch_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    lesson_id BIGINT NULL,
    leave_start_date DATE NOT NULL,
    leave_end_date DATE NOT NULL,
    reason VARCHAR(256) NULL,
    status TINYINT NOT NULL DEFAULT 1 COMMENT '1=待审 2=已批 3=已拒',
    approved_by BIGINT NULL,
    approved_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    version INT NOT NULL DEFAULT 1,
    KEY idx_leave_student (student_id, status),
    KEY idx_leave_status_dates (status, leave_start_date),
    KEY idx_leave_branch (tenant_id, branch_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
